"""Standalone Kaggle kernel templates and a shared terminal progress relay."""


class KernelTemplates:
    """CPU preparation, GPU training, and embedding worker sources."""

    REMOTE_COMMAND_RUNNER = r'''def sh(command, **kwargs):
    """Relay a real terminal so tqdm's disable=None bars remain enabled."""
    import codecs
    import errno
    import pty
    import termios

    print("+ " + " ".join(str(part) for part in command), flush=True)
    input_text = kwargs.pop("input", None)
    kwargs.pop("text", None)
    master, slave = pty.openpty()
    termios.tcsetwinsize(slave, (LANE["limits"]["terminal_rows"],
                               LANE["limits"]["terminal_columns"]))
    WORKING.mkdir(parents=True, exist_ok=True)
    try:
        with (WORKING / LANE["files"]["worker_log"]).open("a", encoding="utf-8") as log:
            with subprocess.Popen([str(part) for part in command],
                                  stdin=subprocess.PIPE if input_text is not None else subprocess.DEVNULL,
                                  stdout=slave, stderr=subprocess.STDOUT,
                                  **kwargs) as process:
                os.close(slave)
                slave = None
                try:
                    if input_text is not None:
                        process.stdin.write(input_text.encode("utf-8"))
                        process.stdin.close()
                    decoder = codecs.getincrementaldecoder("utf-8")("replace")
                    while True:
                        try:
                            chunk = os.read(master, LANE["limits"]["read_buffer_bytes"])
                        except OSError as error:
                            if error.errno != errno.EIO:
                                raise
                            chunk = b""
                        text = decoder.decode(chunk, final=not chunk)
                        print(text, end="", flush=True)
                        log.write(text)
                        log.flush()
                        if not chunk:
                            break
                    rc = process.wait()
                except BaseException:
                    process.terminate()
                    try:
                        process.wait(timeout=LANE["limits"]["child_stop_seconds"])
                    except subprocess.TimeoutExpired:
                        process.kill()
                        process.wait()
                    raise
    finally:
        os.close(master)
        if slave is not None:
            os.close(slave)
    if rc:
        raise subprocess.CalledProcessError(rc, command)

'''


    SIZE_HELPER = r'''def file_size(path):
    """Byte size of a sealed/attached archive member.

    PINNED STANDALONE COPY (the one allowed copy outside ``core``): a kernel
    source is a deployment artifact that runs from /kaggle/working against the
    clone's own checkout, so it must not import the repo package before the
    checkout exists; ``cli.kaggle_kernel_templates`` therefore injects this ONE
    definition into every kernel that measures an archive member (previously
    duplicated verbatim in the bundle and train kernels). It is the same
    structural measure as ``core.portable_archive.file_size``; no content is
    fingerprinted anywhere (owner directive 2026-10-08).
    """
    import os
    return os.path.getsize(path)

'''


    SESSION_REPORT_HELPER = r'''def report_kernel_session():
    """Self-report the kernel session id so the host-side follower persists it.

    PINNED STANDALONE COPY (same allowance as ``file_size`` above): a kernel
    script is a deployment artifact that runs before the repo checkout (and for
    the laya fine-tune kernel WITHOUT one), so it cannot import the lane
    package. Its host-side twin is ``cli.laya_lane.container_session_id`` (the
    id inside ``KAGGLE_CONTAINER_NAME``, ``kaggle_<token>-<session_id>-webtier``),
    which is the numeric id the SDK ``cancel_kernel_session`` accepts; the two
    parses are pinned together by tests/test_kaggle_lane.py, so one rule never
    becomes two. Kaggle sets NO ``KAGGLE_KERNEL_RUN_ID``/``KAGGLE_SESSION_ID``
    in the container, so this line is the only id source the SSE log follower
    (cli.kaggle_monitor) can persist for the verified in-place stop.

    The return shape is the one the laya fine-tune receipt records:
    ``session_id`` is the digit string ("" when the container name is absent or
    malformed), ``KAGGLE_CONTAINER_NAME`` the raw name.
    """
    container = os.environ.get("KAGGLE_CONTAINER_NAME", "")
    parts = container.rsplit("-", 2)
    session_id = parts[1] if len(parts) == 3 and parts[1].isdigit() else ""
    print("[kaggle-session] session_id=" + session_id
          + " container=" + container, flush=True)
    return {"KAGGLE_CONTAINER_NAME": container, "session_id": session_id}

'''


    BUNDLE_KERNEL_SCRIPT = '''\
"""ER bundle generation on a Kaggle CPU session (generated by cli.kaggle_lane).

Owner ruling 2026-10-06: bundle generation is CPU-only and runs here, not
locally; the GPU session only trains. Clones the pinned revision (partial +
sparse checkout), installs the worker requirements, runs
training.prepare_all end-to-end, and stages the launch package plus its
receipt into /kaggle/working for hash-verified fetch-back.
"""
from core.portable_archive import ByteCount
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

LANE = json.loads(@LANE_JSON@)

REPOSITORY = "@REPOSITORY@"
BRANCH = "@BRANCH@"
REVISION = "@REVISION@"
CHECKOUT_PATHS = @CHECKOUT_PATHS@
REQUIREMENTS = "@REQUIREMENTS@"
COHORT = "@COHORT@"
COHORT_DATASET = "@COHORT_DATASET@"

SCRATCH = (Path(LANE["remote"]["scratch_dir"]) if Path(LANE["remote"]["scratch_dir"]).is_dir()
           else Path(tempfile.gettempdir()) / LANE["remote"]["fallback_scratch"].format(kind="bundle"))
WORKING = Path(LANE["remote"]["working_dir"])

@COMMAND_RUNNER@
@SIZE_HELPER@
@SESSION_REPORT@
report_kernel_session()
SCRATCH.mkdir(parents=True, exist_ok=True)
root = SCRATCH / LANE["files"]["checkout_dir"]
if root.exists():
    shutil.rmtree(root)
sh(["git", "clone", "--filter=blob:none", "--no-checkout", "--depth", str(LANE["limits"]["git_clone_depth"]),
    "--branch", BRANCH, REPOSITORY, root])
head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=root,
                      capture_output=True, text=True, check=True).stdout.strip()
if head != REVISION:
    raise SystemExit(
        "branch tip moved: cloned %s but the kernel pins %s; regenerate the "
        "kernel (cli.kaggle_lane --what bundle-kernel)" % (head, REVISION))
# Use the same explicit runtime inventory and sparse mode as Colab.
sh(["git", "-C", str(root), "sparse-checkout", "set", "--no-cone", "--stdin"],
   input="\\n".join("/" + member for member in CHECKOUT_PATHS) + "\\n", text=True)
sh(["git", "-C", str(root), "checkout", BRANCH])
@RUNTIME_PREFLIGHT@
if COHORT != LANE["default_cohort"]:
    source = root / COHORT_DATASET
    if not source.is_file():
        raise SystemExit(
            f"cohort export {COHORT_DATASET} not in the branch checkout for "
            f"cohort {COHORT}; commit it at the repository root or attach it "
            "as a dataset")
    shutil.copy2(source, root / LANE["packaged_data_name"])
    print(f"[bundle-cpu] cohort remap: {COHORT_DATASET} -> dataset.csv", flush=True)
sh([sys.executable, "-m", "pip", "install", "-q", "-r", REQUIREMENTS], cwd=root)
env = {**os.environ, "PYTHONPATH": str(root / LANE["files"]["source_dir"]), "PYTHONUNBUFFERED": "1",
       "ER_COHORT_TAG": COHORT if COHORT != LANE["default_cohort"] else ""}
sh([sys.executable, "-u", "-m", "training.prepare_all",
    "--tracks-config", LANE["files"]["prep_suite_config"]], cwd=root, env=env)
runs = sorted((root / LANE["paths"]["results_dir"] / LANE["files"]["prep_dir"]).glob("*/" + LANE["files"]["bundle_archive"]),
              key=lambda path: path.stat().st_mtime)
if not runs:
    raise SystemExit("prepare_all produced no all_tracks_inputs.tar.zst")
run_dir = runs[-1].parent
destination = WORKING / LANE["files"]["bundle_dir"]
destination.mkdir(parents=True, exist_ok=True)
shutil.copy2(runs[-1], destination / LANE["files"]["bundle_archive"])
for name in LANE["files"]["bundle_sidecars"]:
    sidecar = run_dir / name
    if sidecar.is_file():
        shutil.copy2(sidecar, destination / name)
receipt = {
    "revision": REVISION,
    "branch": BRANCH,
    "run_dir": run_dir.name,
    "cohort": COHORT,
    "cohort_dataset": COHORT_DATASET,
    "archive": LANE["files"]["bundle_archive"],
    "archive_bytes": (destination / LANE["files"]["bundle_archive"]).stat().st_size,
    "archive_size": file_size(destination / LANE["files"]["bundle_archive"]),
}
(destination / LANE["files"]["bundle_receipt"]).write_text(
    json.dumps(receipt, indent=2) + "\\n", encoding="utf-8")
print("[bundle-cpu] receipt: " + json.dumps(receipt, indent=2), flush=True)
'''


    TRAIN_KERNEL_SHARED = '''\
import json
import os
import shutil
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

LANE = json.loads(@LANE_JSON@)

REPOSITORY = "@REPOSITORY@"
BRANCH = "@BRANCH@"
REVISION = "@REVISION@"
CHECKOUT_PATHS = @CHECKOUT_PATHS@
REQUIREMENTS = "@REQUIREMENTS@"
RUN_TAG = "@RUN_TAG@"
SUITE_CONFIG = "@SUITE_CONFIG@"
BUNDLE_KERNEL_SLUG = "@BUNDLE_KERNEL_SLUG@"
BUNDLE_DATASET_NAME = "@BUNDLE_DATASET_NAME@"

WORKING = Path(LANE["remote"]["working_dir"])
INPUTS = Path(LANE["remote"]["input_dir"])
SCRATCH = (Path(LANE["remote"]["scratch_dir"]) if Path(LANE["remote"]["scratch_dir"]).is_dir()
           else Path(tempfile.gettempdir()) / LANE["remote"]["fallback_scratch"].format(kind="gpu"))
BUNDLE_RECEIPT = LANE["files"]["bundle_receipt"]
BUNDLE_ARCHIVE = LANE["files"]["bundle_archive"]

@COMMAND_RUNNER@
@SIZE_HELPER@
@SESSION_REPORT@
report_kernel_session()
def locate_input_archive():
    """Locate the attached bundle output (receipt + archive) under /kaggle/input."""
    candidates = sorted(INPUTS.rglob(BUNDLE_RECEIPT))
    # Kernel-output mounts may hold a stale (stop-stub) version while a
    # bundle dataset stays immutable: prefer the dataset mount when present.
    dataset = next((c for c in candidates
                    if BUNDLE_DATASET_NAME in c.parts), None)
    candidates = [dataset] if dataset is not None else candidates
    if not candidates:
        raise SystemExit("attached outputs contained no " + BUNDLE_RECEIPT)
    receipt_dir = candidates[0].parent
    archive = receipt_dir / BUNDLE_ARCHIVE
    if not archive.is_file():
        raise SystemExit("attached kernel output missing " + BUNDLE_ARCHIVE)
    return archive, receipt_dir

def clone_pinned():
    SCRATCH.mkdir(parents=True, exist_ok=True)
    root = SCRATCH / LANE["files"]["checkout_dir"]
    if root.exists():
        shutil.rmtree(root)
    sh(["git", "clone", "--filter=blob:none", "--no-checkout", "--depth", str(LANE["limits"]["git_clone_depth"]),
        "--branch", BRANCH, REPOSITORY, root])
    head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=root,
                          capture_output=True, text=True, check=True).stdout.strip()
    if head != REVISION:
        raise SystemExit("branch tip moved: cloned %s but the kernel pins %s"
                         % (head, REVISION))
    sh(["git", "-C", str(root), "sparse-checkout", "set", "--no-cone", "--stdin"],
       input="\\n".join("/" + member for member in CHECKOUT_PATHS) + "\\n", text=True)
    sh(["git", "-C", str(root), "checkout", BRANCH])
@RUNTIME_PREFLIGHT@
    sh([sys.executable, "-m", "pip", "install", "-q", "-r", REQUIREMENTS], cwd=root)
    sys.path.insert(0, str(root / LANE["files"]["source_dir"]))
    return root

def stage_result_archive(output: Path, *, kind: str, extra: dict) -> str:
    """Manifest-backed tar.zst + .size companion (colab result-archive mirror).

    The companion lands on the ONE sidecar rule
    (``core.archive_reader.archive_sidecar``).
    """
    result_archive = WORKING / LANE["files"]["result_archive"].format(kind=kind)
    files = sorted(p for p in output.rglob("*") if p.is_file())
    root_name = output.name
    from core.archive_reader import archive_sidecar, tar_archive
    with tar_archive(result_archive, "w") as tar:
        for path in files:
            arcname = Path(root_name) / path.relative_to(output)
            tar.add(path, arcname=str(arcname))
    result_manifest = {
        "kind": kind,
        "run_tag": RUN_TAG,
        "revision": REVISION,
        "files_count": len(files),
        "files": {
            str(Path(root_name) / p.relative_to(output)): {
                "bytes": p.stat().st_size, "size": file_size(p)}
            for p in files
        },
        **extra,
    }
    (WORKING / LANE["files"]["result_manifest"].format(kind=kind)).write_text(
        json.dumps(result_manifest, indent=2), encoding="utf-8")
    digest = file_size(result_archive)
    print(f"[{kind}] staged: {result_archive} size={digest}", flush=True)
    return digest
'''


    TRAIN_KERNEL_BODY = '''
archive_path, receipt_dir = locate_input_archive()
receipt = json.loads((receipt_dir / BUNDLE_RECEIPT).read_text())

root = clone_pinned()
env = {**os.environ, "PYTHONPATH": str(root / LANE["files"]["source_dir"]), "PYTHONUNBUFFERED": "1",
       "ER_COHORT_TAG": receipt.get("cohort", "") or "",
       "WANDB_API_KEY": "@WANDB_API_KEY@"}
# wandb default ON: the key travels with the launch (read locally from .env
# the same way cli.colab does; never logged). Absent key -> core.wandb_ctx
# degrades to local artifacts.

# Install the prepared package exactly where the archive declares members,
# then verify the suite preflight contract file landed at TRAIN_ROOT
# (model_tracks.run ER_GPU_TRAINING_ONLY preflight reads it, run.py:68).
sys.path.insert(0, str(root / LANE["files"]["source_dir"]))
from core.bundle import Bundle

# ONE integrity check for this VM crossing: the attached archive is verified
# once at its Bundle boundary (manifest + every member, by name and byte
# size), and the trusted handle it returns is what the install reads — no
# member is read or re-parsed again.
inputs_bundle = Bundle.load(archive_path, "inputs")
with inputs_bundle.reader() as archive:
    # Code/config neighborhoods are authoritative from the pinned checkout:
    # the bundle's embedded snapshot is built at bundle time and predates the
    # train kernel's revision. Loading its stale config/paths.yaml clobbered
    # the checkout's config and crashed package.py with
    # KeyError: 'source_code_dir' (owner order 2026-10-07). Only the bundle's
    # DATA installs (data/, model_tracks_package.json, artifacts/).
    checkout_authoritative = (LANE["files"]["source_dir"] + "/", "config/", "scripts/")
    for name in archive.namelist():
        if name == LANE["files"]["source_dir"] or name.startswith(checkout_authoritative):
            continue
        archive.extract(name, root)
package_manifest = root / LANE["files"]["package_manifest"]
if not package_manifest.is_file():
    raise SystemExit("package install produced no model_tracks_package.json")
(root / LANE["files"]["package_manifest"]).write_text(package_manifest.read_text(),
                                                encoding="utf-8")

# Consumer side of the ablation contract (owner order: ablation is GPU
# inference). When the suite turns post-training ablation on, the attached
# inputs bundle MUST ship the frozen per-track templates: the GPU worker binds
# them to the selected checkpoint and encodes the ablation vectors on THIS
# device. A bundle that lacks them makes the worker record
# attribute_ablation_export/skipped and pushes the ablation to a local CPU run,
# so the session is refused HERE, before the trainer allocates a GPU.
# `Bundle.ablation_templates` reads the member names the boundary load already
# captured, so this check costs no second archive inflation.
import yaml as _suite_yaml
_suite_config = Path(SUITE_CONFIG)
if not _suite_config.is_absolute():
    _suite_config = root / _suite_config
if (_suite_yaml.safe_load(_suite_config.read_text(encoding="utf-8")) or {}).get(
        "post_training_ablation"):
    from model_tracks.post_training_ablation import ABLATION_TRACKS as _ablation_tracks
    _missing_templates = [track for track in _ablation_tracks
                          if not inputs_bundle.ablation_templates(track)]
    if _missing_templates:
        raise SystemExit(
            "[bundle-contract] post_training_ablation is on but the attached "
            "inputs bundle ships no ablation templates for "
            + ", ".join(_missing_templates)
            + "; the GPU worker would skip the ablation (local CPU fallback). "
            "Rebuild the bundle with the CPU bundling kernel.")
    print("[bundle-contract] ablation templates present for "
          + ", ".join(_ablation_tracks), flush=True)

output = root / LANE["paths"]["results_dir"] / LANE["files"]["training_dir"] / RUN_TAG
env["ER_GPU_TRAINING_ONLY"] = "1"
# Structured training timings ride the result archive (owner order
# 2026-10-07): the same [timing] lines stream live, but timings.json/log are
# also written under output/ so stage_result_archive carries them back.
env["ER_TIMING_OUT"] = str(output / "logs" / "timings.json")
env["ER_TIMING_LOG"] = str(output / "logs" / "timings.log")
sh([sys.executable, "-m", "model_tracks.run",
    "--config", SUITE_CONFIG,
    "--output", str(output), "--run-tag", RUN_TAG], cwd=root, env=env)

stage_result_archive(output, kind=LANE["files"]["result_names"]["train"], extra={
    "bundle_receipt": receipt,
    "bundle_kernel": BUNDLE_KERNEL_SLUG,
    "checkout_paths": CHECKOUT_PATHS,
})
'''


    FINALIZE_KERNEL_BODY = '''
# ── finalize role: ONE remote CPU lane job, run from this sparse checkout ──
# The operator box is no longer a finalize surface (owner ruling): this kernel
# is the only place CPU post-processing, post-training ablation and sealing run.
# Two verified bundles arrive attached and each is integrity-checked exactly
# once, at its Bundle boundary:
#   * the prepared-inputs bundle (the published bundle dataset / CPU kernel
#     output) — role `inputs`; bundle_steps.finalize opens its own SSOT boundary
#     on it, so this kernel neither re-hashes nor re-parses its members;
#   * the trained result bundle (the train kernel output) — role `result`, whose
#     transport digest is pinned here by the one Bundle.load that hands the
#     step its trusted handle.
FINALIZE_MANIFEST = LANE["files"]["result_manifest"].format(
    kind=LANE["files"]["result_names"]["train"])
FINALIZE_ARCHIVE = LANE["files"]["result_archive"].format(
    kind=LANE["files"]["result_names"]["train"])
FINALIZE_RESULT = "@FINALIZE_RESULT_NAME@"

def locate_result_archive():
    """Locate the trained result bundle (manifest + archive) under /kaggle/input."""
    candidates = sorted(INPUTS.rglob(FINALIZE_MANIFEST))
    if not candidates:
        raise SystemExit("attached outputs contained no " + FINALIZE_MANIFEST)
    directory = candidates[0].parent
    archive = directory / FINALIZE_ARCHIVE
    if not archive.is_file():
        raise SystemExit("attached kernel output missing " + FINALIZE_ARCHIVE)
    return archive, json.loads(candidates[0].read_text(encoding="utf-8"))

inputs_archive, inputs_dir = locate_input_archive()
result_archive, result_manifest = locate_result_archive()
inputs_receipt = json.loads((inputs_dir / BUNDLE_RECEIPT).read_text(encoding="utf-8"))

root = clone_pinned()
sys.path.insert(0, str(root / LANE["files"]["source_dir"]))
from core.bundle import Bundle, BundlePipeline
from core.archive_reader import archive_sidecar

# The single boundary check for the result bundle: one load by name and byte
# size, and the handle it returns is what the step consumes (no member is
# re-read afterwards).
result_bundle = Bundle.load(result_archive, "result")
output = (WORKING / LANE["files"]["bundle_dir"]
          / LANE["files"]["result_archive"].format(kind=FINALIZE_RESULT))
work_dir = WORKING / "finalize_work"
pipeline = BundlePipeline(
    role="result", device="cpu", lane="kaggle", output=output,
    inputs=inputs_archive, work_dir=work_dir,
    sparse_paths=tuple(CHECKOUT_PATHS))
sealed = pipeline.finalize(result_bundle)
assert str(sealed.path) == str(output), sealed.path

manifest_name = LANE["files"]["result_manifest"].format(kind=FINALIZE_RESULT)
receipt = {
    "kind": FINALIZE_RESULT,
    "role": "result",
    "run_tag": sealed.run_tag(),
    "revision": REVISION,
    "cohort": inputs_receipt.get("cohort"),
    "archive": output.name,
    "archive_bytes": output.stat().st_size,
    "archive_size": sealed.path.stat().st_size,
    "inputs_size": inputs_receipt.get("archive_size"),
    "result_size": result_bundle.path.stat().st_size,
    "members": len(sealed.members()),
    "postprocess_location": sealed.manifest.get("postprocess_location"),
}
(WORKING / manifest_name).write_text(json.dumps(receipt, indent=2) + "\\n",
                                     encoding="utf-8")
print("[finalize] sealed " + str(output) + " run_tag=" + str(sealed.run_tag())
      + " members=" + str(len(sealed.members())) + " size=" + str(sealed.path.stat().st_size),
      flush=True)
print("[finalize] receipt: " + json.dumps(receipt, indent=2), flush=True)
'''

    EMBED_KERNEL_BODY = '''
# Embedding objective: encode the prepared token archive against the
# git-shipped checkpoint (artifacts/models rides the sparse checkout).
# The request dataset (request.json + prepared_text.npz) is attached as a
# Kaggle dataset: scripts/encode_prepared_embeddings.py refuses any
# re-composition, so the bytes must match the locally prepared request.
candidates = list(INPUTS.rglob(LANE["files"]["request_file"]))
if not candidates:
    raise SystemExit("attached dataset contained no request.json")
request_dir = candidates[0].parent
root = clone_pinned()
checkpoint = root / "@CHECKPOINT@"
if not checkpoint.is_dir():
    raise SystemExit("git-shipped checkpoint missing: " + str(checkpoint))
env = {**os.environ, "PYTHONPATH": str(root / LANE["files"]["source_dir"]), "PYTHONUNBUFFERED": "1"}
output = root / LANE["paths"]["results_dir"] / LANE["files"]["embedding_dir"] / RUN_TAG
output.mkdir(parents=True, exist_ok=True)
sh([sys.executable, LANE["files"]["embedding_script"],
    "--request", str(request_dir / LANE["files"]["request_file"]),
    "--checkpoint", str(checkpoint),
    "--output", str(output / LANE["files"]["vectors_file"]),
    "--device", "cuda"], cwd=root, env=env)
stage_result_archive(output, kind=LANE["files"]["result_names"]["embed"], extra={
    "request_dir": str(request_dir),
    "checkpoint": "@CHECKPOINT@",
})
'''


    @staticmethod
    def substitute(script, values):
        """Replace every ``@TOKEN@`` in ``script`` from ``values`` (ONE home).

        The shared payload substitution: the laya lane's ``_template`` is this
        same loop, and ``render_runtime`` is the runtime-specific caller. A
        token absent from a caller's mapping is left untouched, so a caller may
        substitute in passes (the laya two-pass preflight bake) as before.
        """
        for token, replacement in values.items():
            script = script.replace(f"@{token}@", replacement)
        return script

    @classmethod
    def render_runtime(cls, script, spec):
        """Freeze the lane and shared path/archive SSOT into a standalone worker."""
        import json
        from core.common import data_cfg, training_cfg

        payload = spec.model_dump(mode="json")
        payload["paths"] = data_cfg().paths.model_dump(mode="json")
        payload["archives"] = training_cfg().archives.model_dump(mode="json")
        return cls.substitute(script, {
            "COMMAND_RUNNER": cls.REMOTE_COMMAND_RUNNER,
            "SIZE_HELPER": cls.SIZE_HELPER,
            "LANE_JSON": repr(json.dumps(payload)),
        })


REMOTE_COMMAND_RUNNER = KernelTemplates.REMOTE_COMMAND_RUNNER
SESSION_REPORT_HELPER = KernelTemplates.SESSION_REPORT_HELPER
BUNDLE_KERNEL_SCRIPT = KernelTemplates.BUNDLE_KERNEL_SCRIPT
TRAIN_KERNEL_SHARED = KernelTemplates.TRAIN_KERNEL_SHARED
TRAIN_KERNEL_BODY = KernelTemplates.TRAIN_KERNEL_BODY
FINALIZE_KERNEL_BODY = KernelTemplates.FINALIZE_KERNEL_BODY
EMBED_KERNEL_BODY = KernelTemplates.EMBED_KERNEL_BODY
